spring.application.name=nexus_atlas_api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

com.example.jwtSecret=${JWT_SECRET}
com.example.jwtExpirationMs=${JWT_EXPIRATION}